In [15]:
# using pythin list
import numpy as np
import time
size=1_000_000;
l1=list(range(size))
l2=list(range(size))
start=time.time()
add=[x+y for x,y in zip(l1,l2)]
end=time.time()

print(end-start)

0.16501450538635254


In [19]:
# using numpy array
import numpy as np
import time
size=1_000_000;
l1=np.array(list(range(size)))
l2=np.array(list(range(size)))
start=time.time()
add=l1+l2
print(add)
end=time.time()

print(end-start)

[      0       2       4 ... 1999994 1999996 1999998]
0.007134437561035156


In [5]:
l1=[1,2,4]

In [7]:
l2=[6,7,8]

In [9]:
list(zip(l1,l2))

[(1, 6), (2, 7), (4, 8)]

In [21]:
np.array([2,4,5,6,7,8,9,1])

array([2, 4, 5, 6, 7, 8, 9, 1])

In [25]:
arr=np.array([[1,2,3],[3,4,5]])

In [27]:
type(arr)

numpy.ndarray

In [29]:
arr.shape

(2, 3)

In [37]:
op=[2,2,2,2,2]

# For list comprehension in pure Python
timeStart1 = time.time()
list_sequence = [x**2 for x in op]
print("List Comprehension Result:", list_sequence)
timeEnd1 = time.time()

#for list compreantion of Numpy
np_op=np.array(op) # first we want to make python list to Array of Numpy
timeStart2 = time.time()
numpy_sequence = np_op ** 2
print("NumPy Result:", numpy_sequence)
timeEnd2 = time.time()

# calculate time for each :
# Optional: Print time taken
print("Time for list comprehension:", timeEnd1 - timeStart1, "seconds")
print("Time for NumPy operation:", timeEnd2 - timeStart2, "seconds")




List Comprehension Result: [4, 4, 4, 4, 4]
NumPy Result: [4 4 4 4 4]
Time for list comprehension: 0.0 seconds
Time for NumPy operation: 0.0009996891021728516 seconds


# HOMEWORK

Create a NumPy array with values from 10 to 100 and print its shape.

In [52]:
arr=np.arange(10,100)# 'arange' this is used to make an array of given size

print("Array:",arr)
print("Shape:",arr.shape)

Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Shape: (90,)


Compare the time taken to multiply two Python lists vs. two NumPy arrays.

In [59]:
#for list comprention

size = 1_000_000
l1 = list(range(size))
l2 = list(range(size))
starting_time_list=time.time()
list_multipliaction=[a*b for a,b in zip(l1,l2)]
ending_time_list=time.time()

# for  numpy
array1=np.array(l1)
array2=np.array(l2)
starting_time_numpy=time.time()
array_result=array1* array2
ending_time_numpy=time.time()

#calculate times
print(f"The Time Taken Using Python list : {ending_time_list-starting_time_list} Seconds")
print(f"The Time Taken Using numpy list : {ending_time_numpy-starting_time_numpy} Seconds")



The Time Taken Using Python list : 0.09599924087524414 Seconds
The Time Taken Using numpy list : 0.0020003318786621094 Seconds


Find the memory size of a NumPy array with 1 million elements.

In [72]:
import numpy as np

# create an array of 1 million sizw
array=np.arange(1_000_000)

#get memory size
memory_size=array.nbytes

#convert to kilobite and megabite 
memory_kb=memory_size/1024
memory_mb=memory_kb/1024

print(f"Memory size in kilobytes : {memory_kb:.2f} KB")
print(f"Memory size in megabytes : {memory_mb:.1f} MB")

Memory size in kilobytes : 3906.25 KB
Memory size in megabytes : 3.8 MB


How to Create An array in Numpy

In [78]:
import numpy as np
array=np.array([1,2,3,4])
print(array)

[1 2 3 4]
